In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score

In [4]:
diabetes_data = pd.read_csv('diabetes.csv')

In [5]:
diabetes_data.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [6]:
diabetes_data.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [8]:
diabetes_data.shape

(768, 9)

In [11]:
diabetes_data['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [12]:
diabetes_data.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

In [13]:
x = diabetes_data.drop(columns = 'Outcome', axis = 1)
y = diabetes_data['Outcome']

In [14]:
print(x)
print(y)

     Pregnancies  Glucose  BloodPressure  ...   BMI  DiabetesPedigreeFunction  Age
0              6      148             72  ...  33.6                     0.627   50
1              1       85             66  ...  26.6                     0.351   31
2              8      183             64  ...  23.3                     0.672   32
3              1       89             66  ...  28.1                     0.167   21
4              0      137             40  ...  43.1                     2.288   33
..           ...      ...            ...  ...   ...                       ...  ...
763           10      101             76  ...  32.9                     0.171   63
764            2      122             70  ...  36.8                     0.340   27
765            5      121             72  ...  26.2                     0.245   30
766            1      126             60  ...  30.1                     0.349   47
767            1       93             70  ...  30.4                     0.315   23

[768 rows x 8 columns]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [7]:
scalar = StandardScaler()

In [15]:
standardized_data = scalar.fit_transform(x)

In [16]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [17]:
x = standardized_data

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, stratify = y, random_state = 2)

In [21]:
print(x.shape, x_train.shape, x_test.shape)

(768, 8) (614, 8) (154, 8)

In [25]:
models = {
    "Logistic Regression" : LogisticRegression(),
    "SVM" : svm.SVC(kernel = 'linear'),
    "Random Forest" : RandomForestClassifier(n_estimators = 100, max_depth = 5, min_samples_split = 5, random_state = 42)
}

In [26]:
for name, model in models.items():
  print(f"\n {name}")
  print("-" * 30)
  model.fit(x_train, y_train)
  x_train_pred = model.predict(x_train)
  train_accuracy = accuracy_score(x_train_pred, y_train)
  print('accuracy score of the training data : ', train_accuracy)
  x_test_pred = model.predict(x_test)
  test_accuracy = accuracy_score(x_test_pred, y_test)
  print('accuracy score of the test data : ', test_accuracy)

 Logistic Regression
------------------------------
accuracy score of the training data :  0.7850162866449512
accuracy score of the test data :  0.7597402597402597

 SVM
------------------------------
accuracy score of the training data :  0.7866449511400652
accuracy score of the test data :  0.7727272727272727

 Random Forest
------------------------------
accuracy score of the training data :  0.8615635179153095
accuracy score of the test data :  0.7467532467532467

In [29]:
model = svm.SVC(kernel = 'linear')

In [30]:
model.fit(x_train, y_train)
x_train_pred = model.predict(x_train)
train_accuracy = accuracy_score(x_train_pred, y_train)
print('accuracy score of the training data : ', train_accuracy)
x_test_pred = model.predict(x_test)
test_accuracy = accuracy_score(x_test_pred, y_test)
print('accuracy score of the test data : ', test_accuracy)

accuracy score of the training data :  0.7866449511400652
accuracy score of the test data :  0.7727272727272727

In [32]:
input_data = (2,95,70,25,85,24.5,0.3,28)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
std_data = scalar.transform(input_data_reshaped)
print(std_data)
prediction = model.predict(std_data)
print(prediction)
if prediction[0] == 0:
  print("Non - Diabetic")
else:
  print("Diabetic")

[[-0.54791859 -0.81042491  0.04624525  0.27998931  0.04515558 -0.95095236
  -0.51908683 -0.44593516]]
[0]
Non - Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [39]:
# example input taken from chatgpt and the predictions all are correct !!!!
input_data = [
    (2,95,70,25,85,24.5,0.3,28), # 0
    (7,170,80,32,150,35.2,0.8,45), # 1
    (3,160,72,28,120,29.0,0.4,35), # 1
    (0,88,68,20,70,22.0,0.2,24) # 0
]

input_data_as_numpy_array = np.asarray(input_data)
#input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)
std_data = scalar.transform(input_data_as_numpy_array)
print(std_data)
prediction = model.predict(std_data)
print(prediction)
for i, pred in enumerate(prediction):
  if prediction[i] == 0:
    print("Non - Diabetic")
  else:
    print("Diabetic")

[[-0.54791859 -0.81042491  0.04624525  0.27998931  0.04515558 -0.95095236
  -0.51908683 -0.44593516]
 [ 0.93691372  1.53686099  0.56322275  0.71908574  0.60954382  0.40708356
   0.99097251  1.00055664]
 [-0.25095213  1.22388954  0.14964075  0.4681735   0.34905694 -0.37981576
  -0.21707496  0.14967911]
 [-1.14185152 -1.02950492 -0.05715025 -0.03365099 -0.08508786 -1.26825047
  -0.8210987  -0.78628618]]
[0 1 1 0]
Non - Diabetic
Diabetic
Diabetic
Non - Diabetic

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(